export const SYMBOL_TO_COINGECKO_ID: Record<string, string> = {
  BTC: "bitcoin",
  ETH: "ethereum",
  USDT: "tether",
  BNB: "binancecoin",
  SOL: "solana",
  ADA: "cardano",
  XRP: "ripple",
  DOT: "polkadot",
  LINK: "chainlink",
  AVAX: "avalanche-2",
  DOGE: "dogecoin",
  SHIB: "shiba-inu",
  LTC: "litecoin",
  TRX: "tron",
  MATIC: "polygon-ecosystem-token",
  UNI: "uniswap",
  AAVE: "aave",
  SUSHI: "sushi",
  COMP: "compound-governance-token",
  MKR: "maker",
  YFI: "yearn-finance",
  BAL: "balancer",
  CRV: "curve-dao-token",
  REN: "republic-protocol",
  OMG: "omg-network",
};