/** Stable API / product codes for /meet broadcast (client + support). */

export const BROADCAST_CODES = {
  ok: "ok",
  notAuthenticated: "broadcast_not_authenticated",
  userNotFound: "broadcast_user_not_found",
  hostMismatch: "broadcast_host_mismatch",
  roomBusy: "broadcast_room_busy",
  noDestinations: "broadcast_no_destinations",
  destinationInvalid: "broadcast_destination_invalid",
  egressFailed: "broadcast_egress_failed",
  stopNoop: "broadcast_stop_noop",
  stuckSessionRecovered: "broadcast_stuck_session_recovered",
  liveSceneNotSupported: "broadcast_scene_not_supported",
  liveSceneSessionNotFound: "broadcast_scene_session_not_found",
  liveSceneNotActive: "broadcast_scene_not_active",
  liveSceneHostMismatch: "broadcast_scene_host_mismatch",
  liveSceneInvalid: "broadcast_scene_invalid",
  overlayNotSupported: "broadcast_overlay_not_supported",
  overlaySessionNotFound: "broadcast_overlay_session_not_found",
  overlayNotActive: "broadcast_overlay_not_active",
  overlayHostMismatch: "broadcast_overlay_host_mismatch",
  overlayInvalid: "broadcast_overlay_invalid",
  scheduleNotSupported: "broadcast_schedule_not_supported",
  scheduleSessionNotFound: "broadcast_schedule_session_not_found",
  scheduleNotActive: "broadcast_schedule_not_active",
  scheduleHostMismatch: "broadcast_schedule_host_mismatch",
  scheduleInvalid: "broadcast_schedule_invalid",
  autoDirectingNotSupported: "broadcast_auto_directing_not_supported",
  autoDirectingSessionNotFound: "broadcast_auto_directing_session_not_found",
  autoDirectingNotActive: "broadcast_auto_directing_not_active",
  autoDirectingHostMismatch: "broadcast_auto_directing_host_mismatch",
  autoDirectingInvalid: "broadcast_auto_directing_invalid",
  broadcastEventNotFound: "broadcast_event_not_found",
  broadcastEventInvalid: "broadcast_event_invalid",
  broadcastEventForbidden: "broadcast_event_forbidden",
  broadcastTimelineTemplateNotFound: "broadcast_timeline_template_not_found",
  broadcastTimelineTemplateInvalid: "broadcast_timeline_template_invalid",
  /** Idempotent start: live session already linked to a different broadcast event. */
  broadcastEventIdempotentConflict: "broadcast_event_idempotent_conflict",
  /**
   * Returned in `ephemeralRtmpIgnoredReason` when the client sent `ephemeralRtmp` but the server returned an
   * existing live session (idempotent) — one-time credentials were not applied.
   */
  ephemeralIgnoredIdempotentActiveSession: "broadcast_ephemeral_ignored_idempotent_active_session",
  broadcastTimelineNotFound: "broadcast_timeline_session_not_found",
  broadcastTimelineForbidden: "broadcast_timeline_forbidden",
  broadcastAnalyticsNotFound: "broadcast_analytics_session_not_found",
  broadcastAnalyticsForbidden: "broadcast_analytics_forbidden",
  broadcastCalendarNotConfigured: "broadcast_calendar_not_configured",
  broadcastCalendarUnsupported: "broadcast_calendar_unsupported",
  broadcastCalendarExternalError: "broadcast_calendar_external_error",
  broadcastCalendarLinkNotFound: "broadcast_calendar_link_not_found",
  broadcastCalendarLinkInvalid: "broadcast_calendar_link_invalid",
  broadcastCalendarSyncConflict: "broadcast_calendar_sync_conflict",
  broadcastAnalyticsDashboardInvalid: "broadcast_analytics_dashboard_invalid",
  broadcastLaunchReadinessInvalid: "broadcast_launch_readiness_invalid",
  broadcastShowPackageInvalid: "broadcast_show_package_invalid",
  broadcastShowPackageNotFound: "broadcast_show_package_not_found",
  broadcastOverlayPackInvalid: "broadcast_overlay_pack_invalid",
  broadcastOverlayPackNotFound: "broadcast_overlay_pack_not_found",
  broadcastGuestCardPackInvalid: "broadcast_guest_card_pack_invalid",
  broadcastGuestCardPackNotFound: "broadcast_guest_card_pack_not_found",
} as const;

export type BroadcastErrorCode = (typeof BROADCAST_CODES)[keyof typeof BROADCAST_CODES];
