-- Bentley Social Lead Intelligence: uploads, parsed leads, analysis runs, per-lead analyses.
-- Analysis-only; no outreach execution. Idempotent CREATE.

CREATE TABLE IF NOT EXISTS `lead_uploads` (
  `id` VARCHAR(36) NOT NULL,
  `userId` INT NOT NULL,
  `filename` VARCHAR(512) NOT NULL DEFAULT '',
  `sourceType` VARCHAR(32) NOT NULL,
  `uploadedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `parsedCount` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
  `rawMetaJson` JSON,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `lead_uploads_user_idx` (`userId`),
  KEY `lead_uploads_uploaded_idx` (`uploadedAt`),
  CONSTRAINT `lead_uploads_user_fk` FOREIGN KEY (`userId`) REFERENCES `marketplace_users` (`id`)
);

CREATE TABLE IF NOT EXISTS `lead_records` (
  `id` VARCHAR(36) NOT NULL,
  `uploadId` VARCHAR(36) NOT NULL,
  `userId` INT NOT NULL,
  `businessName` VARCHAR(512) NOT NULL DEFAULT '',
  `platform` VARCHAR(64) NOT NULL DEFAULT '',
  `handle` VARCHAR(256) NOT NULL DEFAULT '',
  `profileUrl` TEXT,
  `email` VARCHAR(320),
  `websiteUrl` TEXT,
  `notes` TEXT,
  `rawPayloadJson` JSON,
  `normalizedPayloadJson` JSON,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `lead_records_upload_idx` (`uploadId`),
  KEY `lead_records_user_idx` (`userId`),
  CONSTRAINT `lead_records_upload_fk` FOREIGN KEY (`uploadId`) REFERENCES `lead_uploads` (`id`) ON DELETE CASCADE,
  CONSTRAINT `lead_records_user_fk` FOREIGN KEY (`userId`) REFERENCES `marketplace_users` (`id`)
);

CREATE TABLE IF NOT EXISTS `lead_analysis_runs` (
  `id` VARCHAR(36) NOT NULL,
  `uploadId` VARCHAR(36) NOT NULL,
  `userId` INT NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'queued',
  `modelVersion` VARCHAR(64) NOT NULL DEFAULT 'bentley-sli-v1',
  `totalLeads` INT NOT NULL DEFAULT 0,
  `successCount` INT NOT NULL DEFAULT 0,
  `failureCount` INT NOT NULL DEFAULT 0,
  `startedAt` TIMESTAMP NULL,
  `completedAt` TIMESTAMP NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `lead_analysis_runs_upload_idx` (`uploadId`),
  KEY `lead_analysis_runs_user_idx` (`userId`),
  CONSTRAINT `lead_analysis_runs_upload_fk` FOREIGN KEY (`uploadId`) REFERENCES `lead_uploads` (`id`) ON DELETE CASCADE,
  CONSTRAINT `lead_analysis_runs_user_fk` FOREIGN KEY (`userId`) REFERENCES `marketplace_users` (`id`)
);

CREATE TABLE IF NOT EXISTS `lead_analyses` (
  `id` VARCHAR(36) NOT NULL,
  `leadRecordId` VARCHAR(36) NOT NULL,
  `analysisRunId` VARCHAR(36) NOT NULL,
  `accessStatus` VARCHAR(32) NOT NULL DEFAULT 'access_limited',
  `confidenceScore` DECIMAL(6,4) NOT NULL DEFAULT 0.5000,
  `visibilityScore` DECIMAL(6,4) NOT NULL DEFAULT 0.0000,
  `demandScore` DECIMAL(6,4) NOT NULL DEFAULT 0.0000,
  `intentScore` DECIMAL(6,4) NOT NULL DEFAULT 0.0000,
  `frictionScore` DECIMAL(6,4) NOT NULL DEFAULT 0.0000,
  `fitScore` DECIMAL(6,4) NOT NULL DEFAULT 0.0000,
  `opportunityScore` DECIMAL(6,4) NOT NULL DEFAULT 0.0000,
  `businessType` VARCHAR(128) NOT NULL DEFAULT '',
  `maturityStage` VARCHAR(64) NOT NULL DEFAULT '',
  `summary` TEXT,
  `accountSummaryJson` JSON,
  `contentSummaryJson` JSON,
  `commentSummaryJson` JSON,
  `strengthsJson` JSON,
  `weakSpotsJson` JSON,
  `painPointsJson` JSON,
  `repeatedBuyerQuestionsJson` JSON,
  `objectionThemesJson` JSON,
  `demandSignalsJson` JSON,
  `bestOfferAngle` TEXT,
  `suggestedCommentAngle` TEXT,
  `suggestedFollowMessageAngle` TEXT,
  `suggestedEmailAngle` TEXT,
  `suggestedNextMove` TEXT,
  `riskNotesJson` JSON,
  `rawAnalysisJson` JSON,
  `analyzedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `lead_analyses_lead_idx` (`leadRecordId`),
  KEY `lead_analyses_run_idx` (`analysisRunId`),
  CONSTRAINT `lead_analyses_lead_fk` FOREIGN KEY (`leadRecordId`) REFERENCES `lead_records` (`id`) ON DELETE CASCADE,
  CONSTRAINT `lead_analyses_run_fk` FOREIGN KEY (`analysisRunId`) REFERENCES `lead_analysis_runs` (`id`) ON DELETE CASCADE
);
