-- Site Builder Intelligence Repository — adaptive generation memory (structural metadata only; no CRM conversation text).

CREATE TABLE IF NOT EXISTS `site_generation_runs` (
  `id` varchar(36) NOT NULL,
  `userId` int NOT NULL,
  `siteId` varchar(36) NULL,
  `clientId` varchar(36) NULL,
  `pipelineStep` varchar(32) NOT NULL,
  `promptHash` varchar(64) NOT NULL,
  `promptSummary` varchar(512) NULL,
  `industry` varchar(200) NULL,
  `businessName` varchar(200) NULL,
  `primaryOffer` varchar(800) NULL,
  `audience` varchar(800) NULL,
  `ctaGoal` varchar(500) NULL,
  `siteType` varchar(32) NULL,
  `designDirection` varchar(32) NULL,
  `styleIntensity` int NULL,
  `web3VisualMode` tinyint(1) NULL,
  `layoutVariantIndex` int NULL,
  `selectedVariantIndex` int NULL,
  `variantCount` int NULL,
  `rejectedVariantIndicesJson` json NULL,
  `schemaMetadataJson` json NOT NULL,
  `sectionRegistryKeysJson` json NOT NULL,
  `designTokensJson` json NULL,
  `agentAttached` tinyint(1) NOT NULL DEFAULT 0,
  `publishStatus` varchar(32) NULL,
  `leadCount` int NULL,
  `conversionRateBps` int NULL,
  `evaluationScore` int NULL,
  `llmEnriched` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `sgr_user_created` (`userId`, `createdAt`),
  KEY `sgr_user_industry` (`userId`, `industry`),
  KEY `sgr_prompt_hash` (`promptHash`),
  KEY `sgr_score` (`evaluationScore`),
  CONSTRAINT `sgr_user_fk` FOREIGN KEY (`userId`) REFERENCES `marketplace_users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `site_generation_variants` (
  `id` varchar(36) NOT NULL,
  `runId` varchar(36) NOT NULL,
  `variantIndex` int NOT NULL,
  `seed` varchar(191) NULL,
  `schemaHash` varchar(64) NULL,
  `wasSelected` tinyint(1) NOT NULL DEFAULT 0,
  `wasRejected` tinyint(1) NOT NULL DEFAULT 0,
  `evaluationScore` int NULL,
  `layoutFingerprintJson` json NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY (`id`),
  UNIQUE KEY `sgv_run_idx` (`runId`, `variantIndex`),
  KEY `sgv_run` (`runId`),
  CONSTRAINT `sgv_run_fk` FOREIGN KEY (`runId`) REFERENCES `site_generation_runs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `site_variant_feedback` (
  `id` varchar(36) NOT NULL,
  `runId` varchar(36) NULL,
  `variantId` varchar(36) NULL,
  `userId` int NOT NULL,
  `feedbackType` varchar(32) NOT NULL,
  `rating` int NULL,
  `noteSummary` varchar(500) NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY (`id`),
  KEY `svf_user` (`userId`),
  KEY `svf_run` (`runId`),
  KEY `svf_variant` (`variantId`),
  CONSTRAINT `svf_user_fk` FOREIGN KEY (`userId`) REFERENCES `marketplace_users` (`id`),
  CONSTRAINT `svf_run_fk` FOREIGN KEY (`runId`) REFERENCES `site_generation_runs` (`id`) ON DELETE SET NULL,
  CONSTRAINT `svf_variant_fk` FOREIGN KEY (`variantId`) REFERENCES `site_generation_variants` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
