-- Human-only executive decision ledger (no autonomous execution)
CREATE TABLE IF NOT EXISTS `executive_operational_decisions` (
  `id` varchar(36) NOT NULL,
  `adminUserId` int NOT NULL,
  `title` varchar(500) NOT NULL,
  `promptSummary` text NOT NULL,
  `status` enum('open','decided','deferred','superseded') NOT NULL DEFAULT 'open',
  `priority` enum('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
  `sourceKind` enum('manual','decision_request','question','approval') NOT NULL DEFAULT 'manual',
  `threadId` varchar(36),
  `questionMessageId` varchar(36),
  `promotedFromMessageId` varchar(36),
  `approvalId` varchar(36),
  `orderId` varchar(191),
  `clientId` varchar(191),
  `subjectId` varchar(64),
  `department` varchar(32),
  `decisionText` text,
  `decidedAt` timestamp,
  `decidedByAdminUserId` int,
  `deferredUntil` timestamp,
  `deferReason` text,
  `supersededByDecisionId` varchar(36),
  `supersedesDecisionId` varchar(36),
  `metadataJson` text,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `executive_operational_decisions_id` PRIMARY KEY(`id`),
  KEY `executive_operational_decisions_admin_status` (`adminUserId`, `status`),
  KEY `executive_operational_decisions_thread` (`adminUserId`, `threadId`),
  KEY `executive_operational_decisions_order` (`adminUserId`, `orderId`),
  KEY `executive_operational_decisions_message` (`promotedFromMessageId`)
);
