-- Human-coordinated executive operational tasks (no autonomous execution)
CREATE TABLE IF NOT EXISTS `executive_operational_tasks` (
  `id` varchar(36) NOT NULL,
  `adminUserId` int NOT NULL,
  `title` varchar(500) NOT NULL,
  `description` text NOT NULL,
  `status` enum('open','in_progress','blocked','completed','canceled') NOT NULL DEFAULT 'open',
  `priority` enum('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
  `ownerLabel` varchar(64) NOT NULL DEFAULT 'executive_owner',
  `department` varchar(32),
  `recommendedAgent` varchar(64),
  `decisionId` varchar(36),
  `threadId` varchar(36),
  `approvalId` varchar(36),
  `orderId` varchar(191),
  `clientId` varchar(191),
  `subjectId` varchar(64),
  `blockedReason` text,
  `blockedAt` timestamp,
  `dueAt` timestamp,
  `startedAt` timestamp,
  `completedAt` timestamp,
  `dependsOnTaskIdsJson` text,
  `metadataJson` text,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `executive_operational_tasks_id` PRIMARY KEY(`id`),
  KEY `executive_operational_tasks_admin_status` (`adminUserId`, `status`),
  KEY `executive_operational_tasks_thread` (`adminUserId`, `threadId`),
  KEY `executive_operational_tasks_order` (`adminUserId`, `orderId`),
  KEY `executive_operational_tasks_decision` (`adminUserId`, `decisionId`)
);
