// lib/jurisdictions/dapt/data.ts
import type { DaptJurisdiction } from "./schema";

export const DAPT_JURISDICTIONS: DaptJurisdiction[] = [
  {
    stateCode: "AK",
    stateName: "Alaska",
    daptLegislation: "Alaska Trust Act",
    protectionStatute: "Alaska Stat. § 34.40.110(b)",
    rufadaaStatute: "§ 13.55.010",
    residencyRequirement: "Qualified Trustee (Must use AK resident/bank)",
    stateTaxStatus: "0%",
    withdrawalProfile: "Tax-free return of principal (Grantor Trust).",
    notes: "Strong protection; does not easily recognize foreign judgments.",
    tier: "TOP_TIER",
    tags: ["NO_STATE_INCOME_TAX"]
  },
  {
    stateCode: "DE",
    stateName: "Delaware",
    daptLegislation: "Qualified Dispositions in Trust Act",
    protectionStatute: "12 Del. C. § 3572",
    rufadaaStatute: "12 Del. C. § 5001",
    residencyRequirement: "Qualified Trustee (Must use DE resident/bank)",
    stateTaxStatus: "Taxable (unless non-resident beneficiaries)",
    withdrawalProfile: "Tax-free return of principal (Grantor Trust).",
    notes: "Often used for DING trusts to manage state tax exposure.",
    tier: "ADVISORY_ONLY",
    tags: ["LEGACY_JURISDICTION"]
  },
  {
    stateCode: "HI",
    stateName: "Hawaii",
    daptLegislation: "Permitted Transfers in Trust Act",
    protectionStatute: "Haw. Rev. Stat. § 554G-5",
    rufadaaStatute: "HRS § 556A-1",
    residencyRequirement: "Qualified Trustee (Must use HI resident/bank)",
    stateTaxStatus: "Taxable",
    withdrawalProfile: "Standard Grantor Trust rules.",
    notes: "Real estate focused; requires strict solvency analysis.",
    tier: "RESTRICTED",
    tags: ["STRICT_SOLVENCY"]
  },
  {
    stateCode: "MI",
    stateName: "Michigan",
    daptLegislation: "Qualified Dispositions in Trust Act",
    protectionStatute: "Mich. Comp. Laws § 700.1045",
    rufadaaStatute: "MCL § 700.1001",
    residencyRequirement: "Qualified Trustee (Must use MI resident/bank)",
    stateTaxStatus: "Taxable",
    withdrawalProfile: "Standard Grantor Trust rules.",
    notes: "2-year statute of limitations for creditors.",
    tier: "ADVISORY_ONLY",
    tags: ["LOOKBACK_2Y"]
  },
  {
    stateCode: "MS",
    stateName: "Mississippi",
    daptLegislation: "Qualified Disposition in Trust Act",
    protectionStatute: "Miss. Code Ann. § 91-9-703",
    rufadaaStatute: "§ 91-23-1",
    residencyRequirement: "Qualified Trustee (Must use MS resident/bank)",
    stateTaxStatus: "Taxable",
    withdrawalProfile: "Standard Grantor Trust rules.",
    notes: "Newer statute; limited case law history.",
    tier: "ADVISORY_ONLY",
    tags: ["LIMITED_CASELAW"]
  },
  {
    stateCode: "MO",
    stateName: "Missouri",
    daptLegislation: "Missouri Uniform Trust Code",
    protectionStatute: "Mo. Rev. Stat. § 456.5-505.3",
    rufadaaStatute: "§ 472.400",
    residencyRequirement: "Qualified Trustee (Must use MO resident/bank)",
    stateTaxStatus: "Taxable",
    withdrawalProfile: "Standard Grantor Trust rules.",
    notes: "Strong spendthrift clause respect; good for residents.",
    tier: "ADVISORY_ONLY",
    tags: ["SPENDTHRIFT_FRIENDLY"]
  },
  {
    stateCode: "NV",
    stateName: "Nevada",
    daptLegislation: "Spendthrift Trust Act of Nevada",
    protectionStatute: "Nev. Rev. Stat. § 166.170",
    rufadaaStatute: "NRS § 722.010",
    residencyRequirement: "Qualified Trustee (Must use NV resident/bank)",
    stateTaxStatus: "0%",
    withdrawalProfile: "Tax-free return of principal (Grantor Trust).",
    notes: "Top tier; no exception creditors noted; supports NING strategies.",
    tier: "TOP_TIER",
    tags: ["NO_STATE_INCOME_TAX", "TOP_TIER_DAPT", "NING_COMPATIBLE"]
  },
  {
    stateCode: "NH",
    stateName: "New Hampshire",
    daptLegislation: "Qualified Dispositions in Trust Act",
    protectionStatute: "N.H. Rev. Stat. Ann. § 564-D:2",
    rufadaaStatute: "RSA § 564-F:1",
    residencyRequirement: "Qualified Trustee (Must use NH resident/bank)",
    stateTaxStatus: "0% on interest/dividends (general characterization)",
    withdrawalProfile: "Tax-free return of principal (Grantor Trust).",
    notes: "Modern competitive statutes.",
    tier: "TOP_TIER",
    tags: ["LOW_STATE_TAX"]
  },
  {
    stateCode: "OH",
    stateName: "Ohio",
    daptLegislation: "Ohio Legacy Trust Act",
    protectionStatute: "Ohio Rev. Code § 5816.07",
    rufadaaStatute: "ORC § 2137.01",
    residencyRequirement: "Qualified Trustee (Must use OH resident/bank)",
    stateTaxStatus: "Taxable",
    withdrawalProfile: "Standard Grantor Trust rules.",
    notes: "18-month statute of limitations (fast).",
    tier: "ADVISORY_ONLY",
    tags: ["FAST_LIMITATIONS"]
  },
  {
    stateCode: "OK",
    stateName: "Oklahoma",
    daptLegislation: "Family Wealth Preservation Trust Act",
    protectionStatute: "31 Okla. Stat. § 12",
    rufadaaStatute: "58 O.S. § 3101",
    residencyRequirement: "Qualified Trustee (Must use OK resident/bank)",
    stateTaxStatus: "Taxable",
    withdrawalProfile: "Flexible (fact-specific).",
    notes: "Unique: allows certain revocable trusts to be protected (reported cap concept).",
    tier: "RESTRICTED",
    tags: ["UNIQUE_STRUCTURE", "REQUIRES_REVIEW"]
  },
  {
    stateCode: "RI",
    stateName: "Rhode Island",
    daptLegislation: "Qualified Dispositions in Trust Act",
    protectionStatute: "R.I. Gen. Laws § 18-9.2-4",
    rufadaaStatute: "§ 33-27-1",
    residencyRequirement: "Qualified Trustee (Must use RI resident/bank)",
    stateTaxStatus: "Taxable",
    withdrawalProfile: "Standard Grantor Trust rules.",
    notes: "4-year lookback period.",
    tier: "ADVISORY_ONLY",
    tags: ["LOOKBACK_4Y"]
  },
  {
    stateCode: "SD",
    stateName: "South Dakota",
    daptLegislation: "Qualified Dispositions in Trust",
    protectionStatute: "S.D. Codified Laws § 55-16-9",
    rufadaaStatute: "SDCL § 29A-5A-401",
    residencyRequirement: "Qualified Trustee (Must use SD resident/bank)",
    stateTaxStatus: "0%",
    withdrawalProfile: "Tax-free return of principal (Grantor Trust).",
    notes: "Top tier; privacy oriented; dynasty trusts long duration.",
    tier: "TOP_TIER",
    tags: ["NO_STATE_INCOME_TAX", "TOP_TIER_DAPT", "PRIVACY_FOCUSED"]
  },
  {
    stateCode: "TN",
    stateName: "Tennessee",
    daptLegislation: "Investment Services Trust Act",
    protectionStatute: "Tenn. Code Ann. § 35-16-104",
    rufadaaStatute: "§ 35-8-101",
    residencyRequirement: "Qualified Trustee (Must use TN resident/bank)",
    stateTaxStatus: "0% (commonly characterized for certain categories)",
    withdrawalProfile: "Tax-free return of principal (Grantor Trust).",
    notes: "Often ranked highly for trust administration.",
    tier: "TOP_TIER",
    tags: ["LOW_STATE_TAX", "ADMIN_FRIENDLY"]
  },
  {
    stateCode: "UT",
    stateName: "Utah",
    daptLegislation: "Utah Domestic Asset Protection Trust Act",
    protectionStatute: "Utah Code § 75B-1-302",
    rufadaaStatute: "§ 75-11-101",
    residencyRequirement: "Qualified Trustee (Must use UT resident/bank)",
    stateTaxStatus: "Taxable",
    withdrawalProfile: "Standard Grantor Trust rules.",
    notes: "2-year statute of limitations.",
    tier: "ADVISORY_ONLY",
    tags: ["LOOKBACK_2Y"]
  },
  {
    stateCode: "VA",
    stateName: "Virginia",
    daptLegislation: "Self-Settled Spendthrift Trusts",
    protectionStatute: "Va. Code Ann. § 64.2-745.1",
    rufadaaStatute: "§ 64.2-116",
    residencyRequirement: "Qualified Trustee (Must use VA resident/bank)",
    stateTaxStatus: "Taxable",
    withdrawalProfile: "Standard Grantor Trust rules.",
    notes: "Historically described as weaker than NV/SD; fact-intensive.",
    tier: "RESTRICTED",
    tags: ["WEAKER_PROTECTION", "REQUIRES_REVIEW"]
  },
  {
    stateCode: "WV",
    stateName: "West Virginia",
    daptLegislation: "West Virginia Permitted Dispositions",
    protectionStatute: "W. Va. Code § 44D-5-503b",
    rufadaaStatute: "§ 44D-8A-1",
    residencyRequirement: "Qualified Trustee (Must use WV resident/bank)",
    stateTaxStatus: "Taxable",
    withdrawalProfile: "Standard Grantor Trust rules.",
    notes: "4-year lookback period.",
    tier: "ADVISORY_ONLY",
    tags: ["LOOKBACK_4Y"]
  },
  {
    stateCode: "WY",
    stateName: "Wyoming",
    daptLegislation: "Uniform Trust Code (Spendthrift)",
    protectionStatute: "Wyo. Stat. Ann. § 4-10-517",
    rufadaaStatute: "§ 2-3-1001",
    residencyRequirement: "Qualified Trustee (Must use WY resident/bank)",
    stateTaxStatus: "0%",
    withdrawalProfile: "Tax-free return of principal (Grantor Trust).",
    notes: "Top tier; private trust company options commonly highlighted.",
    tier: "TOP_TIER",
    tags: ["NO_STATE_INCOME_TAX", "TOP_TIER_DAPT", "PTC_FRIENDLY"]
  }
];