#!/usr/bin/env python3
import json
import sys
from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch

def draw_multiline(c, text, x, y, max_width_chars=95, leading=14):
    words = (text or "").split()
    lines = []
    line = []
    for w in words:
        if len(" ".join(line + [w])) <= max_width_chars:
            line.append(w)
        else:
            lines.append(" ".join(line))
            line = [w]
    if line:
        lines.append(" ".join(line))
    for ln in lines:
        c.drawString(x, y, ln)
        y -= leading
    return y

def main():
    if len(sys.argv) != 3:
        print("Usage: generate_deed_checklist_pdf.py <input_json_path> <output_pdf_path>", file=sys.stderr)
        sys.exit(2)

    input_path = sys.argv[1]
    output_path = sys.argv[2]

    with open(input_path, "r", encoding="utf-8") as f:
        payload = json.load(f)

    c = canvas.Canvas(output_path, pagesize=LETTER)
    width, height = LETTER

    x = 1 * inch
    y = height - 1 * inch

    title = payload.get("title") or "Deed Prep Checklist + Recording Instructions"
    c.setFont("Helvetica-Bold", 14)
    c.drawString(x, y, title)
    y -= 0.2 * inch
    c.setFont("Helvetica", 9)
    c.drawString(x, y, "For internal preparation only. Not legal advice.")
    y -= 0.25 * inch

    c.setFont("Helvetica", 10)
    c.drawString(x, y, f"Deed Type: {payload.get('deedType','')}")
    y -= 0.18 * inch
    c.drawString(x, y, f"Property State: {payload.get('state','')}")
    y -= 0.25 * inch

    prop = payload.get("property", {})
    c.setFont("Helvetica-Bold", 11)
    c.drawString(x, y, "Property")
    y -= 0.18 * inch
    c.setFont("Helvetica", 10)
    addr = ", ".join([p for p in [prop.get("street1"), prop.get("city"), prop.get("state"), prop.get("postalCode")] if p])
    c.drawString(x, y, f"Address: {addr or '—'}")
    y -= 0.16 * inch
    c.drawString(x, y, f"County: {prop.get('county') or '—'}")
    y -= 0.16 * inch
    c.drawString(x, y, f"Parcel/APN: {prop.get('parcelNumber') or '—'}")
    y -= 0.25 * inch

    c.setFont("Helvetica-Bold", 11)
    c.drawString(x, y, "Parties")
    y -= 0.18 * inch
    c.setFont("Helvetica", 10)
    for party in payload.get("parties", []):
        role = party.get("role", "")
        name = party.get("displayName", "")
        c.drawString(x, y, f"{role}: {name}")
        y -= 0.16 * inch
    y -= 0.1 * inch

    legal = prop.get("legalDescription") or ""
    c.setFont("Helvetica-Bold", 11)
    c.drawString(x, y, "Legal Description")
    y -= 0.18 * inch
    c.setFont("Helvetica", 10)
    y = draw_multiline(c, legal if legal else "—", x, y)
    y -= 0.25 * inch

    c.setFont("Helvetica-Bold", 11)
    c.drawString(x, y, "Preparation Checklist")
    y -= 0.18 * inch
    c.setFont("Helvetica", 10)
    checklist = payload.get("checklist", [])
    for item in checklist:
        c.drawString(x, y, f"• {item}")
        y -= 0.16 * inch
    y -= 0.2 * inch

    c.setFont("Helvetica-Bold", 11)
    c.drawString(x, y, "Recording Instructions")
    y -= 0.18 * inch
    c.setFont("Helvetica", 10)
    instructions = payload.get("recordingInstructions", [])
    for item in instructions:
        c.drawString(x, y, f"• {item}")
        y -= 0.16 * inch
    y -= 0.2 * inch

    c.setFont("Helvetica-Bold", 11)
    c.drawString(x, y, "State References")
    y -= 0.18 * inch
    c.setFont("Helvetica", 9)
    for citation in payload.get("citations", []):
        y = draw_multiline(c, f"- {citation.get('label','')}: {citation.get('url','')}", x, y, max_width_chars=100, leading=12)
    y -= 0.2 * inch

    c.setFont("Helvetica", 9)
    c.drawString(x, 0.75 * inch, "Generated by the Deeds module. Verify local law, lender, and recorder requirements.")
    c.drawString(x, 0.65 * inch, "This checklist is for preparation only and is not a recordable instrument.")
    c.save()

if __name__ == "__main__":
    main()
