/**
 * Trust Records Compliance Pack API
 * POST: Generate a PDF compliance pack for brokerage deposit
 * Documents: Trustee Authorization, Asset Certificate, Instrument Summary, Brokerage Cover Letter
 */
import { NextRequest, NextResponse } from "next/server";
import { and, eq } from "drizzle-orm";
import { getDb } from "@/lib/db";
import {
  trusts,
  trustBrokerageAccounts,
  trustAssetInstruments,
  trustAssetEvents,
  trustParties,
} from "@/lib/db/schema";
import { getAuthedUserId } from "@/lib/api/auth";

export async function POST(req: NextRequest) {
  const userId = await getAuthedUserId();
  if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  let body: { trustId: string; assetId?: string; brokerageAccountId?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const { trustId, assetId, brokerageAccountId } = body;
  if (!trustId) return NextResponse.json({ error: "trustId is required" }, { status: 400 });

  const db = await getDb();
  const trustRows = await db
    .select()
    .from(trusts)
    .where(and(eq(trusts.id, trustId), eq(trusts.userId, userId)))
    .limit(1);
  if (trustRows.length === 0) return NextResponse.json({ error: "Trust not found" }, { status: 404 });

  const trust = trustRows[0];

  // Fetch parties for trustee name
  const partyRows = await db
    .select()
    .from(trustParties)
    .where(eq(trustParties.trustId, trustId));
  const trustee = partyRows.find((p) => p.role === "trustee");

  let brokerageAccount: { institution?: string; accountNumber?: string } | null = null;
  if (brokerageAccountId) {
    const accRows = await db
      .select()
      .from(trustBrokerageAccounts)
      .where(
        and(
          eq(trustBrokerageAccounts.trustId, trustId),
          eq(trustBrokerageAccounts.id, brokerageAccountId)
        )
      )
      .limit(1);
    if (accRows.length > 0) {
      const row = accRows[0];
      brokerageAccount = {
        institution: row.institution ?? undefined,
        accountNumber: row.accountNumber ?? undefined,
      };
    }
  }

  let instrument: typeof trustAssetInstruments.$inferSelect | null = null;
  if (assetId) {
    const instRows = await db
      .select()
      .from(trustAssetInstruments)
      .where(eq(trustAssetInstruments.assetId, assetId))
      .limit(1);
    if (instRows.length > 0) instrument = instRows[0];
  }

  // Generate HTML pack (can be upgraded to PDF via puppeteer or similar)
  const trustName = trust.name ?? "Trust";
  const trusteeName = trustee?.displayName ?? "Trustee";

  const trusteeLetter = `
<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Trustee Authorization Letter</title></head>
<body style="font-family: Georgia, serif; max-width: 600px; margin: 40px auto; line-height: 1.6;">
  <h2>Trustee Authorization Letter</h2>
  <p>Date: ${new Date().toISOString().slice(0, 10)}</p>
  <p>Re: ${trustName}</p>
  <p>This letter certifies that ${trusteeName} is duly authorized as Trustee of the above-named trust to direct deposits of trust assets into brokerage accounts held in the trust's name.</p>
  <p>This authorization is issued for the purpose of facilitating the deposit of trust assets and is valid for the transaction(s) described in the accompanying documentation.</p>
  <p>Respectfully,</p>
  <p><strong>${trusteeName}</strong><br/>Trustee</p>
</body></html>`;

  const assetCertificate = `
<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Asset Deposit Certificate</title></head>
<body style="font-family: Georgia, serif; max-width: 600px; margin: 40px auto; line-height: 1.6;">
  <h2>Asset Deposit Certificate</h2>
  <p>Date: ${new Date().toISOString().slice(0, 10)}</p>
  <p>Trust: ${trustName}</p>
  <p>Asset ID: ${assetId ?? "N/A"}</p>
  <p>This certificate confirms that the above-referenced asset is held by the trust and is being deposited in accordance with the trust instrument and applicable procedures.</p>
  <p>Generated by Trust Records Platform. This is a record-keeping document, not a legal opinion.</p>
</body></html>`;

  const instrumentSummary = instrument
    ? `
<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Instrument Summary Sheet</title></head>
<body style="font-family: Georgia, serif; max-width: 600px; margin: 40px auto; line-height: 1.6;">
  <h2>Instrument Summary Sheet</h2>
  <p>Date: ${new Date().toISOString().slice(0, 10)}</p>
  <table style="width:100%; border-collapse: collapse;">
    <tr><td style="border:1px solid #ccc; padding:8px;"><strong>Instrument Type</strong></td><td style="border:1px solid #ccc; padding:8px;">${instrument.instrumentType ?? "—"}</td></tr>
    <tr><td style="border:1px solid #ccc; padding:8px;"><strong>Issuer</strong></td><td style="border:1px solid #ccc; padding:8px;">${instrument.issuer ?? "—"}</td></tr>
    <tr><td style="border:1px solid #ccc; padding:8px;"><strong>Face Value</strong></td><td style="border:1px solid #ccc; padding:8px;">${instrument.faceValue ?? "—"}</td></tr>
    <tr><td style="border:1px solid #ccc; padding:8px;"><strong>Issue Date</strong></td><td style="border:1px solid #ccc; padding:8px;">${instrument.issueDate ?? "—"}</td></tr>
    <tr><td style="border:1px solid #ccc; padding:8px;"><strong>Transferability</strong></td><td style="border:1px solid #ccc; padding:8px;">${instrument.transferability ?? "—"}</td></tr>
    <tr><td style="border:1px solid #ccc; padding:8px;"><strong>CUSIP</strong></td><td style="border:1px solid #ccc; padding:8px;">${instrument.cusip ?? "—"}</td></tr>
    <tr><td style="border:1px solid #ccc; padding:8px;"><strong>Transfer Agent</strong></td><td style="border:1px solid #ccc; padding:8px;">${instrument.transferAgent ?? "—"}</td></tr>
  </table>
</body></html>`
    : "<html><body><p>No instrument metadata on file.</p></body></html>";

  const brokerageLetter = brokerageAccount
    ? `
<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Brokerage Cover Letter</title></head>
<body style="font-family: Georgia, serif; max-width: 600px; margin: 40px auto; line-height: 1.6;">
  <h2>Brokerage Cover Letter</h2>
  <p>Date: ${new Date().toISOString().slice(0, 10)}</p>
  <p>To: ${brokerageAccount.institution ?? "Brokerage Institution"}</p>
  <p>Account: ${brokerageAccount.accountNumber ?? "—"}</p>
  <p>Re: Deposit of Trust Assets — ${trustName}</p>
  <p>Please find enclosed the trustee authorization, asset certificate, and instrument summary for the deposit of trust assets into the above-referenced account.</p>
  <p>This documentation is provided for your records and to facilitate the deposit process. Please contact the trustee with any questions.</p>
</body></html>`
    : "<html><body><p>No brokerage account specified.</p></body></html>";

  // Return combined HTML (client can print/save as PDF, or we can add server-side PDF generation)
  const combined = `
<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Compliance Pack — ${trustName}</title>
<style>section { page-break-after: always; } section:last-child { page-break-after: auto; }</style>
</head>
<body>
  <section>${trusteeLetter}</section>
  <section>${assetCertificate}</section>
  <section>${instrumentSummary}</section>
  <section>${brokerageLetter}</section>
</body></html>`;

  return new NextResponse(combined, {
    status: 200,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `inline; filename="compliance-pack-${trustId.slice(0, 8)}.html"`,
    },
  });
}
